version: '3.8'

services:
  weather-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    restart: unless-stopped
    networks:
      - weather-network

networks:
  weather-network:
    driver: bridge
